import { RootDependency } from '@/components/RootDependency'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { AppProvider } from './provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'PMO Lagos state',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
				<link
					href="https://fonts.googleapis.com/css2?family=Quicksand:wght@200;300;400;500;600;700;800&display=swap"
					rel="stylesheet"
				/>
			</head>
      <body className={inter.className}><RootDependency><AppProvider>{children}</AppProvider></RootDependency></body>
    </html>
  )
}
